version: '2'
services:
  db-za:
    image: postgres:9.4.1
    ports:
      - "5433:5432"

  redis-za:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"

  web:
    image: adiprod
    command: bin/rails server -e production --port 3000 --binding 0.0.0.0
    environment:
      - SECRET_KEY_BASE
      - RAILS_LOG_TO_STDOUT=1  #TODO setup logging
      - RAILS_SERVE_STATIC_FILES=1
    ports:
      - "3003:3000"
    links:
      - db-za
    volumes:
      - .:/adiapp
